package entities;
// Generated Nov 7, 2017 7:36:03 PM by Hibernate Tools 4.3.1



/**
 * Banner generated by hbm2java
 */
public class Banner  implements java.io.Serializable {


     private Integer bannerMa;
     private String bannerTen;
     private String bannerAnh;
     private String bannerTinhtrang;

    public Banner() {
    }

    public Banner(String bannerTen, String bannerAnh, String bannerTinhtrang) {
       this.bannerTen = bannerTen;
       this.bannerAnh = bannerAnh;
       this.bannerTinhtrang = bannerTinhtrang;
    }
   
    public Integer getBannerMa() {
        return this.bannerMa;
    }
    
    public void setBannerMa(Integer bannerMa) {
        this.bannerMa = bannerMa;
    }
    public String getBannerTen() {
        return this.bannerTen;
    }
    
    public void setBannerTen(String bannerTen) {
        this.bannerTen = bannerTen;
    }
    public String getBannerAnh() {
        return this.bannerAnh;
    }
    
    public void setBannerAnh(String bannerAnh) {
        this.bannerAnh = bannerAnh;
    }
    public String getBannerTinhtrang() {
        return this.bannerTinhtrang;
    }
    
    public void setBannerTinhtrang(String bannerTinhtrang) {
        this.bannerTinhtrang = bannerTinhtrang;
    }




}


