package entities;
// Generated Nov 7, 2017 7:36:03 PM by Hibernate Tools 4.3.1



/**
 * Cauhoi generated by hbm2java
 */
public class Cauhoi  implements java.io.Serializable {


     private Integer cauhoiMa;
     private String cauhoiAnh;
     private String cauhoiNoidung;
     private String cauhoiDapana;
     private String cauhoiDapanb;
     private String cauhoiDapanc;
     private String cauhoiDapan;
     private String cauhoiGiaithich;
     private String cauhoiThamkhao;
     private String cauhoiHangthi;

    public Cauhoi() {
    }

    public Cauhoi(String cauhoiAnh, String cauhoiNoidung, String cauhoiDapana, String cauhoiDapanb, String cauhoiDapanc, String cauhoiDapan, String cauhoiGiaithich, String cauhoiThamkhao, String cauhoiHangthi) {
       this.cauhoiAnh = cauhoiAnh;
       this.cauhoiNoidung = cauhoiNoidung;
       this.cauhoiDapana = cauhoiDapana;
       this.cauhoiDapanb = cauhoiDapanb;
       this.cauhoiDapanc = cauhoiDapanc;
       this.cauhoiDapan = cauhoiDapan;
       this.cauhoiGiaithich = cauhoiGiaithich;
       this.cauhoiThamkhao = cauhoiThamkhao;
       this.cauhoiHangthi = cauhoiHangthi;
    }
   
    public Integer getCauhoiMa() {
        return this.cauhoiMa;
    }
    
    public void setCauhoiMa(Integer cauhoiMa) {
        this.cauhoiMa = cauhoiMa;
    }
    public String getCauhoiAnh() {
        return this.cauhoiAnh;
    }
    
    public void setCauhoiAnh(String cauhoiAnh) {
        this.cauhoiAnh = cauhoiAnh;
    }
    public String getCauhoiNoidung() {
        return this.cauhoiNoidung;
    }
    
    public void setCauhoiNoidung(String cauhoiNoidung) {
        this.cauhoiNoidung = cauhoiNoidung;
    }
    public String getCauhoiDapana() {
        return this.cauhoiDapana;
    }
    
    public void setCauhoiDapana(String cauhoiDapana) {
        this.cauhoiDapana = cauhoiDapana;
    }
    public String getCauhoiDapanb() {
        return this.cauhoiDapanb;
    }
    
    public void setCauhoiDapanb(String cauhoiDapanb) {
        this.cauhoiDapanb = cauhoiDapanb;
    }
    public String getCauhoiDapanc() {
        return this.cauhoiDapanc;
    }
    
    public void setCauhoiDapanc(String cauhoiDapanc) {
        this.cauhoiDapanc = cauhoiDapanc;
    }
    public String getCauhoiDapan() {
        return this.cauhoiDapan;
    }
    
    public void setCauhoiDapan(String cauhoiDapan) {
        this.cauhoiDapan = cauhoiDapan;
    }
    public String getCauhoiGiaithich() {
        return this.cauhoiGiaithich;
    }
    
    public void setCauhoiGiaithich(String cauhoiGiaithich) {
        this.cauhoiGiaithich = cauhoiGiaithich;
    }
    public String getCauhoiThamkhao() {
        return this.cauhoiThamkhao;
    }
    
    public void setCauhoiThamkhao(String cauhoiThamkhao) {
        this.cauhoiThamkhao = cauhoiThamkhao;
    }
    public String getCauhoiHangthi() {
        return this.cauhoiHangthi;
    }
    
    public void setCauhoiHangthi(String cauhoiHangthi) {
        this.cauhoiHangthi = cauhoiHangthi;
    }




}


