package entities;
// Generated Nov 7, 2017 7:36:03 PM by Hibernate Tools 4.3.1



/**
 * Dmtl generated by hbm2java
 */
public class Dmtl  implements java.io.Serializable {


     private Integer dmtlMa;
     private String dmtlTen;

    public Dmtl() {
    }

    public Dmtl(String dmtlTen) {
       this.dmtlTen = dmtlTen;
    }
   
    public Integer getDmtlMa() {
        return this.dmtlMa;
    }
    
    public void setDmtlMa(Integer dmtlMa) {
        this.dmtlMa = dmtlMa;
    }
    public String getDmtlTen() {
        return this.dmtlTen;
    }
    
    public void setDmtlTen(String dmtlTen) {
        this.dmtlTen = dmtlTen;
    }




}


