package entities;
// Generated Nov 7, 2017 7:36:03 PM by Hibernate Tools 4.3.1



/**
 * Hoso generated by hbm2java
 */
public class Hoso  implements java.io.Serializable {


     private Integer hosoMa;
     private String hosoTen;
     private String hosoCmnd;
     private String hosoSdt;
     private String hosoEmail;
     private String hosoHangthi;
     private String hosoAnhcmnd;
     private String hosoAnhchandung;
     private String hosoSuckhoe;
     private String hosoNgaylap;
     private String hosoNgaythi;
     private String hosoDiadiem;

    public Hoso() {
    }

    public Hoso(String hosoTen, String hosoCmnd, String hosoSdt, String hosoEmail, String hosoHangthi, String hosoAnhcmnd, String hosoAnhchandung, String hosoSuckhoe, String hosoNgaylap, String hosoNgaythi, String hosoDiadiem) {
       this.hosoTen = hosoTen;
       this.hosoCmnd = hosoCmnd;
       this.hosoSdt = hosoSdt;
       this.hosoEmail = hosoEmail;
       this.hosoHangthi = hosoHangthi;
       this.hosoAnhcmnd = hosoAnhcmnd;
       this.hosoAnhchandung = hosoAnhchandung;
       this.hosoSuckhoe = hosoSuckhoe;
       this.hosoNgaylap = hosoNgaylap;
       this.hosoNgaythi = hosoNgaythi;
       this.hosoDiadiem = hosoDiadiem;
    }
   
    public Integer getHosoMa() {
        return this.hosoMa;
    }
    
    public void setHosoMa(Integer hosoMa) {
        this.hosoMa = hosoMa;
    }
    public String getHosoTen() {
        return this.hosoTen;
    }
    
    public void setHosoTen(String hosoTen) {
        this.hosoTen = hosoTen;
    }
    public String getHosoCmnd() {
        return this.hosoCmnd;
    }
    
    public void setHosoCmnd(String hosoCmnd) {
        this.hosoCmnd = hosoCmnd;
    }
    public String getHosoSdt() {
        return this.hosoSdt;
    }
    
    public void setHosoSdt(String hosoSdt) {
        this.hosoSdt = hosoSdt;
    }
    public String getHosoEmail() {
        return this.hosoEmail;
    }
    
    public void setHosoEmail(String hosoEmail) {
        this.hosoEmail = hosoEmail;
    }
    public String getHosoHangthi() {
        return this.hosoHangthi;
    }
    
    public void setHosoHangthi(String hosoHangthi) {
        this.hosoHangthi = hosoHangthi;
    }
    public String getHosoAnhcmnd() {
        return this.hosoAnhcmnd;
    }
    
    public void setHosoAnhcmnd(String hosoAnhcmnd) {
        this.hosoAnhcmnd = hosoAnhcmnd;
    }
    public String getHosoAnhchandung() {
        return this.hosoAnhchandung;
    }
    
    public void setHosoAnhchandung(String hosoAnhchandung) {
        this.hosoAnhchandung = hosoAnhchandung;
    }
    public String getHosoSuckhoe() {
        return this.hosoSuckhoe;
    }
    
    public void setHosoSuckhoe(String hosoSuckhoe) {
        this.hosoSuckhoe = hosoSuckhoe;
    }
    public String getHosoNgaylap() {
        return this.hosoNgaylap;
    }
    
    public void setHosoNgaylap(String hosoNgaylap) {
        this.hosoNgaylap = hosoNgaylap;
    }
    public String getHosoNgaythi() {
        return this.hosoNgaythi;
    }
    
    public void setHosoNgaythi(String hosoNgaythi) {
        this.hosoNgaythi = hosoNgaythi;
    }
    public String getHosoDiadiem() {
        return this.hosoDiadiem;
    }
    
    public void setHosoDiadiem(String hosoDiadiem) {
        this.hosoDiadiem = hosoDiadiem;
    }




}


