package entities;
// Generated Nov 7, 2017 7:36:03 PM by Hibernate Tools 4.3.1



/**
 * Lythuyet generated by hbm2java
 */
public class Lythuyet  implements java.io.Serializable {


     private Integer lythuyetMa;
     private String lythuyetCmnd;
     private String lythuyetDapan;
     private String lythuyetKetqua;
     private String lythuyetNgaythi;

    public Lythuyet() {
    }

    public Lythuyet(String lythuyetCmnd, String lythuyetDapan, String lythuyetKetqua, String lythuyetNgaythi) {
       this.lythuyetCmnd = lythuyetCmnd;
       this.lythuyetDapan = lythuyetDapan;
       this.lythuyetKetqua = lythuyetKetqua;
       this.lythuyetNgaythi = lythuyetNgaythi;
    }
   
    public Integer getLythuyetMa() {
        return this.lythuyetMa;
    }
    
    public void setLythuyetMa(Integer lythuyetMa) {
        this.lythuyetMa = lythuyetMa;
    }
    public String getLythuyetCmnd() {
        return this.lythuyetCmnd;
    }
    
    public void setLythuyetCmnd(String lythuyetCmnd) {
        this.lythuyetCmnd = lythuyetCmnd;
    }
    public String getLythuyetDapan() {
        return this.lythuyetDapan;
    }
    
    public void setLythuyetDapan(String lythuyetDapan) {
        this.lythuyetDapan = lythuyetDapan;
    }
    public String getLythuyetKetqua() {
        return this.lythuyetKetqua;
    }
    
    public void setLythuyetKetqua(String lythuyetKetqua) {
        this.lythuyetKetqua = lythuyetKetqua;
    }
    public String getLythuyetNgaythi() {
        return this.lythuyetNgaythi;
    }
    
    public void setLythuyetNgaythi(String lythuyetNgaythi) {
        this.lythuyetNgaythi = lythuyetNgaythi;
    }




}


