package entities;
// Generated Nov 7, 2017 7:36:03 PM by Hibernate Tools 4.3.1



/**
 * Nguoidung generated by hbm2java
 */
public class Nguoidung  implements java.io.Serializable {


     private Integer nguoidungMa;
     private String nguoidungTen;
     private String nguoidungNgaysinh;
     private String nguoidungDiachi;
     private String nguoidungCmnd;
     private String nguoidungGioitinh;
     private String nguoidungSdt;
     private String nguoidungEmail;
     private String nguoidungTaikhoan;
     private String nguoidungMatkhau;
     private String nguoidungQuyen;

    public Nguoidung() {
    }

    public Nguoidung(String nguoidungTen, String nguoidungNgaysinh, String nguoidungDiachi, String nguoidungCmnd, String nguoidungGioitinh, String nguoidungSdt, String nguoidungEmail, String nguoidungTaikhoan, String nguoidungMatkhau, String nguoidungQuyen) {
       this.nguoidungTen = nguoidungTen;
       this.nguoidungNgaysinh = nguoidungNgaysinh;
       this.nguoidungDiachi = nguoidungDiachi;
       this.nguoidungCmnd = nguoidungCmnd;
       this.nguoidungGioitinh = nguoidungGioitinh;
       this.nguoidungSdt = nguoidungSdt;
       this.nguoidungEmail = nguoidungEmail;
       this.nguoidungTaikhoan = nguoidungTaikhoan;
       this.nguoidungMatkhau = nguoidungMatkhau;
       this.nguoidungQuyen = nguoidungQuyen;
    }
   
    public Integer getNguoidungMa() {
        return this.nguoidungMa;
    }
    
    public void setNguoidungMa(Integer nguoidungMa) {
        this.nguoidungMa = nguoidungMa;
    }
    public String getNguoidungTen() {
        return this.nguoidungTen;
    }
    
    public void setNguoidungTen(String nguoidungTen) {
        this.nguoidungTen = nguoidungTen;
    }
    public String getNguoidungNgaysinh() {
        return this.nguoidungNgaysinh;
    }
    
    public void setNguoidungNgaysinh(String nguoidungNgaysinh) {
        this.nguoidungNgaysinh = nguoidungNgaysinh;
    }
    public String getNguoidungDiachi() {
        return this.nguoidungDiachi;
    }
    
    public void setNguoidungDiachi(String nguoidungDiachi) {
        this.nguoidungDiachi = nguoidungDiachi;
    }
    public String getNguoidungCmnd() {
        return this.nguoidungCmnd;
    }
    
    public void setNguoidungCmnd(String nguoidungCmnd) {
        this.nguoidungCmnd = nguoidungCmnd;
    }
    public String getNguoidungGioitinh() {
        return this.nguoidungGioitinh;
    }
    
    public void setNguoidungGioitinh(String nguoidungGioitinh) {
        this.nguoidungGioitinh = nguoidungGioitinh;
    }
    public String getNguoidungSdt() {
        return this.nguoidungSdt;
    }
    
    public void setNguoidungSdt(String nguoidungSdt) {
        this.nguoidungSdt = nguoidungSdt;
    }
    public String getNguoidungEmail() {
        return this.nguoidungEmail;
    }
    
    public void setNguoidungEmail(String nguoidungEmail) {
        this.nguoidungEmail = nguoidungEmail;
    }
    public String getNguoidungTaikhoan() {
        return this.nguoidungTaikhoan;
    }
    
    public void setNguoidungTaikhoan(String nguoidungTaikhoan) {
        this.nguoidungTaikhoan = nguoidungTaikhoan;
    }
    public String getNguoidungMatkhau() {
        return this.nguoidungMatkhau;
    }
    
    public void setNguoidungMatkhau(String nguoidungMatkhau) {
        this.nguoidungMatkhau = nguoidungMatkhau;
    }
    public String getNguoidungQuyen() {
        return this.nguoidungQuyen;
    }
    
    public void setNguoidungQuyen(String nguoidungQuyen) {
        this.nguoidungQuyen = nguoidungQuyen;
    }




}


