package entities;
// Generated Nov 7, 2017 7:36:03 PM by Hibernate Tools 4.3.1



/**
 * Tailieu generated by hbm2java
 */
public class Tailieu  implements java.io.Serializable {


     private Integer tailieuMa;
     private String tailieuTen;
     private String tailieuTomtat;
     private String tailieuNoidung;
     private String tailieuDanhmuc;
     private String tailieuTaptin;

    public Tailieu() {
    }

    public Tailieu(String tailieuTen, String tailieuTomtat, String tailieuNoidung, String tailieuDanhmuc, String tailieuTaptin) {
       this.tailieuTen = tailieuTen;
       this.tailieuTomtat = tailieuTomtat;
       this.tailieuNoidung = tailieuNoidung;
       this.tailieuDanhmuc = tailieuDanhmuc;
       this.tailieuTaptin = tailieuTaptin;
    }
   
    public Integer getTailieuMa() {
        return this.tailieuMa;
    }
    
    public void setTailieuMa(Integer tailieuMa) {
        this.tailieuMa = tailieuMa;
    }
    public String getTailieuTen() {
        return this.tailieuTen;
    }
    
    public void setTailieuTen(String tailieuTen) {
        this.tailieuTen = tailieuTen;
    }
    public String getTailieuTomtat() {
        return this.tailieuTomtat;
    }
    
    public void setTailieuTomtat(String tailieuTomtat) {
        this.tailieuTomtat = tailieuTomtat;
    }
    public String getTailieuNoidung() {
        return this.tailieuNoidung;
    }
    
    public void setTailieuNoidung(String tailieuNoidung) {
        this.tailieuNoidung = tailieuNoidung;
    }
    public String getTailieuDanhmuc() {
        return this.tailieuDanhmuc;
    }
    
    public void setTailieuDanhmuc(String tailieuDanhmuc) {
        this.tailieuDanhmuc = tailieuDanhmuc;
    }
    public String getTailieuTaptin() {
        return this.tailieuTaptin;
    }
    
    public void setTailieuTaptin(String tailieuTaptin) {
        this.tailieuTaptin = tailieuTaptin;
    }




}


